// <auto-generated />
using BeeHive.Infra.DataAccess.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeeHive.Infra.Postgres.Migrations
{
    [DbContext(typeof(BeeHiveDbContext))]
    [Migration("20251130165645_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeeHive.Domain.Aggregate.AudioAggregateStatsData", b =>
                {
                    b.Property<int>("TimeAggregateSeriesId")
                        .HasColumnType("integer");

                    b.Property<string>("Timestamp")
                        .HasColumnType("text");

                    b.Property<float>("AmplitudeMav")
                        .HasColumnType("real");

                    b.Property<float>("AmplitudePeak")
                        .HasColumnType("real");

                    b.Property<float>("AmplitudeRms")
                        .HasColumnType("real");

                    b.Property<float>("DurationSec")
                        .HasColumnType("real");

                    b.Property<float>("Frequency")
                        .HasColumnType("real");

                    b.HasKey("TimeAggregateSeriesId", "Timestamp");

                    b.ToTable("AudioAggregateStatsData");
                });

            modelBuilder.Entity("BeeHive.Domain.Aggregate.TimeAggregateSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LasteAggregateTime")
                        .HasColumnType("text");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSeriesId")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TimeSeriesId", "Period")
                        .IsUnique();

                    b.ToTable("TimeAggregateSeries");
                });

            modelBuilder.Entity("BeeHive.Domain.Aggregate.TimeAggregateSeriesData", b =>
                {
                    b.Property<int>("TimeAggregateSeriesId")
                        .HasColumnType("integer");

                    b.Property<string>("Timestamp")
                        .HasColumnType("text");

                    b.Property<float?>("AvgValue")
                        .HasColumnType("real");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedOrUpdatedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("MaxValue")
                        .HasColumnType("real");

                    b.Property<float?>("MedValue")
                        .HasColumnType("real");

                    b.Property<float?>("MinValue")
                        .HasColumnType("real");

                    b.HasKey("TimeAggregateSeriesId", "Timestamp");

                    b.HasIndex("CreatedOrUpdatedDate");

                    b.ToTable("TimeAggregateSeriesData");
                });

            modelBuilder.Entity("BeeHive.Domain.BeeGardens.BeeGarden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HoldingId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId", "UniqueKey")
                        .IsUnique();

                    b.ToTable("BeeGardens");
                });

            modelBuilder.Entity("BeeHive.Domain.BeeGardens.BeeGardenImportState", b =>
                {
                    b.Property<int>("BeeGardenId")
                        .HasColumnType("integer");

                    b.Property<int>("ExportEntity")
                        .HasColumnType("integer");

                    b.Property<string>("LastCreatedOrUpdatedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BeeGardenId", "ExportEntity");

                    b.ToTable("BeeGardenImportStates");
                });

            modelBuilder.Entity("BeeHive.Domain.Data.TimeSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HiveId")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HiveId", "Kind")
                        .IsUnique();

                    b.ToTable("TimeSeries");
                });

            modelBuilder.Entity("BeeHive.Domain.Data.TimeSeriesData", b =>
                {
                    b.Property<int>("TimeSeriesId")
                        .HasColumnType("integer");

                    b.Property<string>("Timestamp")
                        .HasColumnType("text");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("TimeSeriesId", "Timestamp");

                    b.ToTable("TimeSeriesData");
                });

            modelBuilder.Entity("BeeHive.Domain.Hives.Audio.AudioFile", b =>
                {
                    b.Property<int>("HiveId")
                        .HasColumnType("integer");

                    b.Property<string>("Timestamp")
                        .HasColumnType("text");

                    b.Property<float>("AmplitudeMav")
                        .HasColumnType("real");

                    b.Property<float>("AmplitudePeak")
                        .HasColumnType("real");

                    b.Property<float>("AmplitudeRms")
                        .HasColumnType("real");

                    b.Property<int>("BitsPerSample")
                        .HasColumnType("integer");

                    b.Property<int>("Channels")
                        .HasColumnType("integer");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean");

                    b.Property<float>("DurationSec")
                        .HasColumnType("real");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Frequency")
                        .HasColumnType("real");

                    b.Property<int>("SampleRate")
                        .HasColumnType("integer");

                    b.HasKey("HiveId", "Timestamp");

                    b.HasIndex("HiveId", "Complete");

                    b.ToTable("AudioFiles");
                });

            modelBuilder.Entity("BeeHive.Domain.Hives.Hive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AudioSensorBitsPerSample")
                        .HasColumnType("integer");

                    b.Property<int>("AudioSensorChannels")
                        .HasColumnType("integer");

                    b.Property<int>("AudioSensorSampleRate")
                        .HasColumnType("integer");

                    b.Property<int>("BeeGardenId")
                        .HasColumnType("integer");

                    b.Property<string>("ComPort")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedOrUpdatedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GraphColor")
                        .HasColumnType("integer");

                    b.Property<string>("LastComPortUsed")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SerialBound")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOrUpdatedDate");

                    b.HasIndex("BeeGardenId", "UniqueKey")
                        .IsUnique();

                    b.ToTable("Hives");
                });

            modelBuilder.Entity("BeeHive.Domain.Hives.HiveMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedOrUpdatedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HiveId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalPath")
                        .HasColumnType("text");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<int?>("OrginalId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOrUpdatedDate");

                    b.HasIndex("HiveId", "OrginalId");

                    b.ToTable("HiveMedia");
                });

            modelBuilder.Entity("BeeHive.Domain.Holdings.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UniqueKey")
                        .IsUnique();

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("BeeHive.Domain.Aggregate.AudioAggregateStatsData", b =>
                {
                    b.HasOne("BeeHive.Domain.Aggregate.TimeAggregateSeries", "TimeAggregateSeries")
                        .WithMany("AudioStats")
                        .HasForeignKey("TimeAggregateSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeAggregateSeries");
                });

            modelBuilder.Entity("BeeHive.Domain.Aggregate.TimeAggregateSeries", b =>
                {
                    b.HasOne("BeeHive.Domain.Data.TimeSeries", "TimeSeries")
                        .WithMany()
                        .HasForeignKey("TimeSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeSeries");
                });

            modelBuilder.Entity("BeeHive.Domain.Aggregate.TimeAggregateSeriesData", b =>
                {
                    b.HasOne("BeeHive.Domain.Aggregate.TimeAggregateSeries", "TimeAggregateSeries")
                        .WithMany("Data")
                        .HasForeignKey("TimeAggregateSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeAggregateSeries");
                });

            modelBuilder.Entity("BeeHive.Domain.BeeGardens.BeeGarden", b =>
                {
                    b.HasOne("BeeHive.Domain.Holdings.Holding", "Holding")
                        .WithMany()
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("BeeHive.Domain.BeeGardens.BeeGardenImportState", b =>
                {
                    b.HasOne("BeeHive.Domain.BeeGardens.BeeGarden", "BeeGarden")
                        .WithMany()
                        .HasForeignKey("BeeGardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeeGarden");
                });

            modelBuilder.Entity("BeeHive.Domain.Data.TimeSeries", b =>
                {
                    b.HasOne("BeeHive.Domain.Hives.Hive", "Hive")
                        .WithMany()
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hive");
                });

            modelBuilder.Entity("BeeHive.Domain.Data.TimeSeriesData", b =>
                {
                    b.HasOne("BeeHive.Domain.Data.TimeSeries", "TimeSeries")
                        .WithMany("Data")
                        .HasForeignKey("TimeSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeSeries");
                });

            modelBuilder.Entity("BeeHive.Domain.Hives.Audio.AudioFile", b =>
                {
                    b.HasOne("BeeHive.Domain.Hives.Hive", "Hive")
                        .WithMany()
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hive");
                });

            modelBuilder.Entity("BeeHive.Domain.Hives.Hive", b =>
                {
                    b.HasOne("BeeHive.Domain.BeeGardens.BeeGarden", "BeeGarden")
                        .WithMany()
                        .HasForeignKey("BeeGardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeeGarden");
                });

            modelBuilder.Entity("BeeHive.Domain.Hives.HiveMedia", b =>
                {
                    b.HasOne("BeeHive.Domain.Hives.Hive", "Hive")
                        .WithMany("Media")
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hive");
                });

            modelBuilder.Entity("BeeHive.Domain.Aggregate.TimeAggregateSeries", b =>
                {
                    b.Navigation("AudioStats");

                    b.Navigation("Data");
                });

            modelBuilder.Entity("BeeHive.Domain.Data.TimeSeries", b =>
                {
                    b.Navigation("Data");
                });

            modelBuilder.Entity("BeeHive.Domain.Hives.Hive", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
